# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x05unary\"\xd7\x01\n\x0fInventoryRecord\x12\x14\n\x0cInventory_ID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x03 \x01(\t\x12\r\n\x05Price\x18\x04 \x01(\x01\x12\x19\n\x11Quantity_in_Stock\x18\x05 \x01(\x05\x12\x17\n\x0fInventory_Value\x18\x06 \x01(\x05\x12\x15\n\rReorder_Level\x18\x07 \x01(\x05\x12\x1b\n\x13Quantity_in_Reorder\x18\x08 \x01(\x05\x12\x14\n\x0c\x44iscontinued\x18\t \x01(\x08\"\x1e\n\x10InventoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x16InventorySearchRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_value\x18\x02 \x01(\t\"Y\n\x15InventoryRangeRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x17\n\x0fkey_value_start\x18\x02 \x01(\t\x12\x15\n\rkey_value_end\x18\x03 \x01(\t\";\n\x13\x44istributionRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x12\n\npercentile\x18\x02 \x01(\x01\"[\n\rUpdateRequest\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_value\x18\x02 \x01(\t\x12\x10\n\x08val_name\x18\x03 \x01(\t\x12\x13\n\x0bval_val_new\x18\x04 \x01(\t\"%\n\x14\x44istributionResponse\x12\r\n\x05value\x18\x01 \x01(\x01\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xdc\x02\n\x10InventoryService\x12=\n\nsearchByID\x12\x17.unary.InventoryRequest\x1a\x16.unary.InventoryRecord\x12?\n\x06search\x12\x1d.unary.InventorySearchRequest\x1a\x16.unary.InventoryRecord\x12\x45\n\x0bsearchRange\x12\x1c.unary.InventoryRangeRequest\x1a\x16.unary.InventoryRecord0\x01\x12J\n\x0fgetDistribution\x12\x1a.unary.DistributionRequest\x1a\x1b.unary.DistributionResponse\x12\x35\n\x06update\x12\x14.unary.UpdateRequest\x1a\x15.unary.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORYRECORD']._serialized_start=27
  _globals['_INVENTORYRECORD']._serialized_end=242
  _globals['_INVENTORYREQUEST']._serialized_start=244
  _globals['_INVENTORYREQUEST']._serialized_end=274
  _globals['_INVENTORYSEARCHREQUEST']._serialized_start=276
  _globals['_INVENTORYSEARCHREQUEST']._serialized_end=337
  _globals['_INVENTORYRANGEREQUEST']._serialized_start=339
  _globals['_INVENTORYRANGEREQUEST']._serialized_end=428
  _globals['_DISTRIBUTIONREQUEST']._serialized_start=430
  _globals['_DISTRIBUTIONREQUEST']._serialized_end=489
  _globals['_UPDATEREQUEST']._serialized_start=491
  _globals['_UPDATEREQUEST']._serialized_end=582
  _globals['_DISTRIBUTIONRESPONSE']._serialized_start=584
  _globals['_DISTRIBUTIONRESPONSE']._serialized_end=621
  _globals['_UPDATERESPONSE']._serialized_start=623
  _globals['_UPDATERESPONSE']._serialized_end=656
  _globals['_INVENTORYSERVICE']._serialized_start=659
  _globals['_INVENTORYSERVICE']._serialized_end=1007
# @@protoc_insertion_point(module_scope)
